/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "zc_messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ZC_VERSION, zc_version_t, AUTO)


PB_BIND(ZC_TEMPERATURE, zc_temperature_t, AUTO)


PB_BIND(ZC_STATUS, zc_status_t, AUTO)


PB_BIND(ZC_CURVE_POINT, zc_curve_point_t, AUTO)


PB_BIND(ZC_CSOM_MOD_CONFIG, zc_csom_mod_config_t, AUTO)


PB_BIND(ZC_CSOM_CONFIG, zc_csom_config_t, AUTO)


PB_BIND(ZC_CURVE_CONFIG, zc_curve_config_t, AUTO)


PB_BIND(ZC_OCP_CONFIG, zc_ocp_config_t, AUTO)


PB_BIND(ZC_OUVP_CONFIG, zc_ouvp_config_t, AUTO)


PB_BIND(ZC_OUFP_CONFIG, zc_oufp_config_t, AUTO)


PB_BIND(ZC_COAP_CONFIG, zc_coap_config_t, AUTO)


PB_BIND(ZC_CALIB_CONFIG, zc_calib_config_t, AUTO)


PB_BIND(ZC_CONFIG, zc_config_t, AUTO)


PB_BIND(ZC_VERSION_REQUEST, zc_version_request_t, AUTO)


PB_BIND(ZC_STATUS_REQUEST, zc_status_request_t, AUTO)


PB_BIND(ZC_DEVICE_CMD_REQUEST, zc_device_cmd_request_t, AUTO)


PB_BIND(ZC_SET_CONFIG_REQUEST, zc_set_config_request_t, AUTO)


PB_BIND(ZC_GET_CURVE_CONFIG_REQUEST, zc_get_curve_config_request_t, AUTO)


PB_BIND(ZC_GET_CSOM_CONFIG_REQUEST, zc_get_csom_config_request_t, AUTO)


PB_BIND(ZC_GET_OCP_CONFIG_REQUEST, zc_get_ocp_config_request_t, AUTO)


PB_BIND(ZC_GET_OUVP_CONFIG_REQUEST, zc_get_ouvp_config_request_t, AUTO)


PB_BIND(ZC_GET_OUFP_CONFIG_REQUEST, zc_get_oufp_config_request_t, AUTO)


PB_BIND(ZC_GET_COAP_CONFIG_REQUEST, zc_get_coap_config_request_t, AUTO)


PB_BIND(ZC_GET_CALIB_CONFIG_REQUEST, zc_get_calib_config_request_t, AUTO)


PB_BIND(ZC_GET_CONFIG_REQUEST, zc_get_config_request_t, AUTO)


PB_BIND(ZC_ERROR, zc_error_t, AUTO)


PB_BIND(ZC_RESPONSE, zc_response_t, AUTO)


PB_BIND(ZC_REQUEST, zc_request_t, AUTO)











