/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "zc_messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ZC_VERSION, zc_version_t, AUTO)


PB_BIND(ZC_TEMPERATURE, zc_temperature_t, AUTO)


PB_BIND(ZC_STATUS, zc_status_t, AUTO)


PB_BIND(ZC_CURVE_POINT, zc_curve_point_t, AUTO)


PB_BIND(ZC_CSOM_MOD_CONFIG, zc_csom_mod_config_t, AUTO)


PB_BIND(ZC_CSOM_CONFIG, zc_csom_config_t, AUTO)


PB_BIND(ZC_CURVE_CONFIG, zc_curve_config_t, AUTO)


PB_BIND(ZC_OCP_CONFIG, zc_ocp_config_t, AUTO)


PB_BIND(ZC_OUVP_CONFIG, zc_ouvp_config_t, AUTO)


PB_BIND(ZC_OUFP_CONFIG, zc_oufp_config_t, AUTO)


PB_BIND(ZC_NOTIF_CONFIG, zc_notif_config_t, AUTO)


PB_BIND(ZC_CALIB_CONFIG, zc_calib_config_t, AUTO)


PB_BIND(ZC_CONFIG, zc_config_t, AUTO)


PB_BIND(ZC_REQUEST_VERSION, zc_request_version_t, AUTO)


PB_BIND(ZC_REQUEST_STATUS, zc_request_status_t, AUTO)


PB_BIND(ZC_REQUEST_DEVICE_CMD, zc_request_device_cmd_t, AUTO)


PB_BIND(ZC_REQUEST_SET_CONFIG, zc_request_set_config_t, AUTO)


PB_BIND(ZC_REQUEST_GET_CONFIG_CURVE, zc_request_get_config_curve_t, AUTO)


PB_BIND(ZC_REQUEST_GET_CONFIG_CSOM, zc_request_get_config_csom_t, AUTO)


PB_BIND(ZC_REQUEST_GET_CONFIG_OCP, zc_request_get_config_ocp_t, AUTO)


PB_BIND(ZC_REQUEST_GET_CONFIG_OUVP, zc_request_get_config_ouvp_t, AUTO)


PB_BIND(ZC_REQUEST_GET_CONFIG_OUFP, zc_request_get_config_oufp_t, AUTO)


PB_BIND(ZC_REQUEST_GET_CONFIG_NOTIF, zc_request_get_config_notif_t, AUTO)


PB_BIND(ZC_REQUEST_GET_CONFIG_CALIB, zc_request_get_config_calib_t, AUTO)


PB_BIND(ZC_REQUEST_GET_CONFIG, zc_request_get_config_t, AUTO)


PB_BIND(ZC_ERROR, zc_error_t, AUTO)


PB_BIND(ZC_RESPONSE, zc_response_t, AUTO)


PB_BIND(ZC_REQUEST, zc_request_t, AUTO)


PB_BIND(ZC_MESSAGE, zc_message_t, AUTO)











